### ISSUE TITLE
Move to Geotools 21+ to enable Java 11+?

### ISSUE THREAD

**Issue by integratedmodelling** [TheHortonMachine/hortonmachine#55]
Hortonmachine still depends on GT 20.0. It is currently the only package that holds up a long-due upgrade of our stack so we can move out from Java 8 on to a modular architecture. Is there any plan to move to GT 21 or beyond, so that Java 11 becomes an option?

Thank you!
ferdinando

**Comment by moovida** [comment]
Hi Ferdinando, your timing is right, thanks for getting in touch. We might have gotten a small funding (still evaluating) to migrate to java 13. Around 20 minutes ago (really timing) I started preparing an email to the geotools list to understand how well java > 11 is supported, but then I didn't send it because I wanted to document my self better and had no time right now. 

You seem to have experience with java 11 and geotools, so would you be available to lend a hand? It would be mainly to solve doubts, not asking to actively develop :-) But you are sure welcome if you want to. What do you think?

**Comment by integratedmodelling** [comment]
Thanks Andrea. Our team doesn't have Java 11 experience other than a need to move out of obsoleted requirements - so we're pretty much in the same situation as you, with the need to learn and all. But we'd b love to open a Java 11 develop branch so we can give the whole thing a good stress test, as our infrastructure (www.integratedmodelling.org and around) uses GT and hortonmachine a lot. In general, happy to help good projects move forward! Let us know how we can help.

**Comment by moovida** [comment]
Ok, so you are not already using geotools > 21, right?
When I did some tests some time ago, I found out that there were issues with some geotools style related classes, that were relying on jre classes that are no longer available. I probably first need to have a look how that was solved in geotools. 

But sure, to have someone that tests some of the models, that would help incredibly. Do you have some models already setup or are you in an initial phase?

Anyways, I will keep this issue updated as I move on, so that we can discuss, if there is need to.

**Comment by integratedmodelling** [comment]
No, stuck on 20, thanks to you :)

We use hortonmachine code as part of our online semantic modeling platform. Mainly morphological and hydrological calculations, watershed extraction and some of the lesto algorithms. We have 13 researchers and ~600 users testing the code daily (and unknowingly) in all kinds of situations and terrains, so if it survives us, it will probably survive everything.

Let us know here what needs testing and we can take it from there. Good luck!

**Comment by moovida** [comment]
Fantastic!!!! I love the integratedmodelling platform. A pity I didn't know of it earlier. 

I will let you know when I start, maybe you can drop me an email, some of the discussions might have more sense off-the-issue in order to not pollute it.

**Comment by moovida** [comment]
This is not done and default.
